### PR TITLE
Address memory leaks in libxdifile

### PR DESCRIPTION
**Pull request by bruceravel**
So, I've been asked talk about XDI at the thing in Hamburg before the XAFS conference, so I want to give some attention to libxdifile.

This PR is the result of analysis of libxdifile (and xdi_reader -- there were a couple leaks there) using Valgrind.  I can now get xdi_reader to run on all good and bad data examples as intended and without any problems of the sort flagged by Valgrind.

I wrote a small perl test program using [Test::More](https://metacpan.org/pod/Test::More) (so much easier to use than nose!) to verify the Valgrind cleanliness of each of the test files.  That is in the `c/` folder.

Also in this PR are some updates to the perl wrapper (needed for Athena).  With no memory leaks in libxdifile, the perl wrapper is now quite reliable.  (It was very crashy before.)

I can't imagine that there will be any objection to this PR, but I'll wait a day or two before merging it.

### CODE REVIEW

**Comment by newville** [comment]
Great! I'll try this with Python this week, and update the Larch code to use this.

**Comment by bruceravel** [comment]
There aren't any changes to the API, so it should be completely transparent when you try it with python.  Wait -- that's not 100% true.  There is now a method called XDI_cleanup which properly frees all the memory used by the struct.  It has to be called with the error code returned by XDI_readfile so that it knows what parts of the struct have been allocated.  There are examples in xdi_reader.c.

**Comment by newville** [comment]
@bruceravel  I found a might-be-an-issue with XDI_cleanup.  First, *not* using XDI_cleanup, the Python / Larch XDI reader seems to work fine, but it's probably leaking memory.  If I add the XDI_cleanup() calls, I get seg-faults (testing on Mac OS X, will try other systems tomorrow).   But, if I comment out the final  `free(xdifile);` from XDI_cleanup(), it seems to be fine.

I'm not yest sure if this is a Python-specific problem.   But the C examples (and presumably Perl) examples are working OK... Any suggestions?

**Comment by bruceravel** [comment]
My best guess ... person's reference counter knows about the pointer to profile, but does not know that the call to XDI_cleanup has already removed it.  Perhaps XDI_cleanup should **not** free the profile pointer itself.  So xdi_reader would have to call XDI_cleanup then free the pointer. In the context of py or pl, call cleanup,then let the garbage collector take care of the rest.

Not that I actually understand memory management, or any such thing....

**Comment by bruceravel** [comment]
Frickin' autocorrect!  That's xdifile, not profile... :angry:

**Comment by bruceravel** [comment]
@newville, I am back at my desk now.  I see exactly the same behavior in Perl.  With the `free(xdifile)` line, I get a segfault.  Without, the test suite exits in a way that (I think) means that there were no memory problems.

In `xdr_reader.c`, moving the `free(xdifile);` line to the main program works fine, unsurprisingly.

I propose that that line be removed from `XDI_cleanup` and the documentation be adjusted accordingly.  That is, I think that `XDI_cleanup` is important for managing the memory, it is just important to leave the last bit of memory management up to the wrapper.

**Comment by newville** [comment]
+1 I think the outer code has to alloc and free the basic XDIfile struct.

**Comment by newville** [comment]
@bruceravel -- sorry if I'm missing something, but just to check:  Are you working on a branch/PR that fixes this, or should I make a PR?   I'm not in a rush or anything, just checking......

**Comment by bruceravel** [comment]
I'm working on a branch that makes validation work in a way I find more sensible.  I can roll this change in with that mountain of changes.  Or you can fix it and advance the master.  All the same to me.


On March 12, 2015, at 2:27 PM, Matt Newville <notifications@github.com> wrote:


@bruceravel<https://github.com/bruceravel> -- sorry if I'm missing something, but just to check: Are you working on a branch/PR that fixes this, or should I make a PR? I'm not in a rush or anything, just checking......

**Comment by newville** [comment]
If you're working on a branch and have that change in there, that's fine with me.

**Comment by bruceravel** [comment]
OK, then.  I have made that change in the "validation" branch.  It's working great at the level of C -- I am pretty happy with how validation works and it all runs Valgrind-clean.  I need to update the perl wrapper and its tests.  I also need to write some more documentation.  Should have something for you to look at sometime soon-ish.

**Pull request merged**
