### PR TITLE
Warning codes

### PR DESCRIPTION
**Pull request by bruceravel**
Numeric codes returned from `XDI_validate_item` used to be 1,2,4,8,etc -- that is, intended to be interpreted bitwise.  That method is now intended to be called on a single metadata item at a time, so bitwise warning codes don't make sense.  The warning codes are now incremented integers starting at 100.

This PR also includes a few small changes to the perl wrapper.

### CODE REVIEW

**Comment by newville** [comment]
bitwise warnings could let you identify more than one problem at a time.  I think the code doesn't do this now, but rather returns on first error.   But, it could (in principle, at some point) be modified to return an error code that does include multiple errors, if the error codes are bitmasks.    It's hard to imagine having more 30 distinct error codes.

So, I think this is OK to change. I can imagine someone could come along at some point and want to change them all back to bitmasks.   I can't imagine that being me.

**Comment by bruceravel** [comment]
The method is `XDI_validate_item` -- singular.  It takes one metadata 
item, validates it, and returns a warning code.  The intent is that one 
loops over all the metadata, validates each item, and responds 
appropriately to each code that is returned.

One certainly could write a method that loops over all the metadata 
items, validates them all, and returns a code that must be interpretaed 
bitwise. That would be a different method.  And it would be easy to 
compute a bit mask from the warning codes.

The reason I wrote it that way was so that validation would be as 
granular as possible and as easy to ignore as possible.  It's all 
reasonably well documented in `lib/README.md`.


On 07/29/2015 11:32 AM, Matt Newville wrote:
> bitwise warnings could let you identify more than one problem at a time.
> I think the code doesn't do this now, but rather returns on first error.
> But, it could (in principle, at some point) be modified to return an
> error code that does include multiple errors, if the error codes are
> bitmasks. It's hard to imagine having more 30 distinct error codes.
>
> So, I think this is OK to change. I can imagine someone could come along
> at some point and want to change them all back to bitmasks. I can't
> imagine that being me.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/XraySpectroscopy/XAS-Data-Interchange/pull/52#issuecomment-125990429>.
>


-- 
  Bruce Ravel  ------------------------------------ bravel@bnl.gov

  National Institute of Standards and Technology
  Synchrotron Science Group at NSLS-II
  Building 535A
  Upton NY, 11973

  Homepage:    http://bruceravel.github.io/home/
  Software:    https://github.com/bruceravel
  Demeter:     http://bruceravel.github.io/demeter/

**Comment by newville** [comment]
OK, it's just not completely obvious to me why 100+x is better than bitwise.   Then again, I don't really use the "validate metadata" routines, as I am perfectly willing to break several of these rules (or recommendations?).

**Comment by bruceravel** [comment]
On 07/29/2015 12:32 PM, Matt Newville wrote:
> OK, it's just not completely obvious to me why 100+x is better than
> bitwise.

"100,101,102, etc" looks really different from "0,1,2,4, etc"  That's 
all.  There aren't a lot of ways to make integers look different....

> Then again, I don't really use the "validate metadata"
> routines, as I am perfectly willing to break several of these rules (or
> recommendations?).

That's exactly why I abstracted them so far out.  Easy to use, easy to 
not use.


-- 
  Bruce Ravel  ------------------------------------ bravel@bnl.gov

  National Institute of Standards and Technology
  Synchrotron Science Group at NSLS-II
  Building 535A
  Upton NY, 11973

  Homepage:    http://bruceravel.github.io/home/
  Software:    https://github.com/bruceravel
  Demeter:     http://bruceravel.github.io/demeter/

**Pull request merged**
